In [1]:
# https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [2]:
import torch
import numpy as np

In [3]:
# In numpy, we use array. In torch, we use tensor similarly.
# Both have similar functions like: shape, reshape, etc.

In [4]:
x = np.array([[1.0,2.0], [3.0,4.0]])

In [5]:
tensor_x = torch.tensor(x, dtype=torch.float32)

In [6]:
tensor_x.shape

torch.Size([2, 2])

In [7]:
x.shape

(2, 2)

In [8]:
tensor_x.dtype

torch.float32

In [9]:
# Especialy, a tensor can be stored at cpu or gpu. We can check by device attribute
tensor_x.device

device(type='cpu')

In [10]:
# we can move our tensor to gpu if we have one.
if torch.cuda.is_available():
    cuda_tensor_x = tensor_x.to('cuda')

In [11]:
tensor_x.device, cuda_tensor_x.device

(device(type='cpu'), device(type='cuda', index=0))

In [12]:
# random a new tensor on cuda
r = torch.rand((2,2), device='cuda')
r

tensor([[0.5113, 0.7616],
        [0.5147, 0.4411]], device='cuda:0')

In [13]:
r.device

device(type='cuda', index=0)

In [19]:
# apply some operations on cuda:
# add
print(r + cuda_tensor_x)
# minux
print(r - cuda_tensor_x)
# multiple elemen wise
print(r * cuda_tensor_x)
# multiple
print(torch.multiply(r, cuda_tensor_x))

tensor([[1.5113, 2.7616],
        [3.5147, 4.4411]], device='cuda:0')
tensor([[-0.4887, -1.2384],
        [-2.4853, -3.5589]], device='cuda:0')
tensor([[0.5113, 1.5233],
        [1.5441, 1.7645]], device='cuda:0')
tensor([[0.5113, 1.5233],
        [1.5441, 1.7645]], device='cuda:0')
