In [1]:
# pytorch support calculate gradient automaticaly.

In [2]:
# We try to solve the linear problem
# a * x + b = y.
# we have sample (x,y) find a and b to minimize RMS error

In [3]:
from torch.autograd import Variable
from torch import Tensor, nn
import torch

In [4]:
a = Variable(torch.rand(1), requires_grad=True)
b = Variable(torch.rand(1), requires_grad=True)

In [5]:
a, b

(tensor([0.3743], requires_grad=True), tensor([0.6167], requires_grad=True))

In [6]:
x = Tensor([3])
y = Tensor([9])

In [7]:
y_hat = a * x + b

In [8]:
y_hat

tensor([1.7395], grad_fn=<AddBackward0>)

In [9]:
loss = nn.MSELoss()(y_hat, y)

In [10]:
loss

tensor(52.7148, grad_fn=<MseLossBackward>)

In [11]:
loss.backward()

In [12]:
lr = 0.01

In [13]:
a.grad, b.grad

(tensor([-43.5630]), tensor([-14.5210]))

In [14]:
# a = a - lr * a.grad
# b = b - lr * b.grad

In [15]:
a.data = a.data - lr * a.grad.data
b.data = b.data - lr * b.grad.data

In [16]:
a, b

(tensor([0.8099], requires_grad=True), tensor([0.7619], requires_grad=True))

In [17]:
y_hat = a * x + b
y_hat

tensor([3.1916], grad_fn=<AddBackward0>)

In [18]:
print(x,y)

tensor([3.]) tensor([9.])


In [19]:
x = Tensor([3])
y = Tensor([9])
a = Variable(Tensor([1]), requires_grad=True)
b = Variable(Tensor([1]), requires_grad=True)

In [20]:
lr = 0.01
MSE = nn.MSELoss()
for i in range(10):
    y_hat = a * x + b
    loss = MSE(y_hat, y)
    loss.backward()
    print(i, 'loss', loss, 'grad', a.grad, b.grad)
    a.data = a.data - lr * a.grad
    b.data = b.data - lr * b.grad
    # zero grad after do backward if we don't want grad is added to the next backward
    a.grad.data.zero_()
    b.grad.data.zero_()

0 loss tensor(25., grad_fn=<MseLossBackward>) grad tensor([-30.]) tensor([-10.])
1 loss tensor(16., grad_fn=<MseLossBackward>) grad tensor([-24.]) tensor([-8.])
2 loss tensor(10.2400, grad_fn=<MseLossBackward>) grad tensor([-19.2000]) tensor([-6.4000])
3 loss tensor(6.5536, grad_fn=<MseLossBackward>) grad tensor([-15.3600]) tensor([-5.1200])
4 loss tensor(4.1943, grad_fn=<MseLossBackward>) grad tensor([-12.2880]) tensor([-4.0960])
5 loss tensor(2.6844, grad_fn=<MseLossBackward>) grad tensor([-9.8304]) tensor([-3.2768])
6 loss tensor(1.7180, grad_fn=<MseLossBackward>) grad tensor([-7.8643]) tensor([-2.6214])
7 loss tensor(1.0995, grad_fn=<MseLossBackward>) grad tensor([-6.2915]) tensor([-2.0972])
8 loss tensor(0.7037, grad_fn=<MseLossBackward>) grad tensor([-5.0332]) tensor([-1.6777])
9 loss tensor(0.4504, grad_fn=<MseLossBackward>) grad tensor([-4.0265]) tensor([-1.3422])
